name: Delete Lambda Layer

on: push

jobs:
  delete:
    name: Delete Unneeded Layer from AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Find regions and versions; delete
        run: |
          BRANCH=${GITHUB_REF##*/}
          RELEASE_LAYER="twitter-bot-$BRANCH"

          echo aws --version

          versions=$(aws lambda list-layer-versions --layer-name "$RELEASE_LAYER" --output text --query LayerVersions[].Version | tr '[:blank:]' '\n')
          for version in $versions;
          do
            echo "deleting arn:aws:lambda:$region:*:layer:$RELEASE_LAYER:$version"
            aws lambda delete-layer-version --layer-name $RELEASE_LAYER --version $version
          done
