name: Deploy Lambda Layer

on:
  push:
    # paths: [requirements.txt]

jobs:
  deploy:
    name: Upload Layer to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # For more info: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Zip up and publish the layer
        run: |
          BRANCH=${GITHUB_REF##*/}
          RELEASE_ID="twitter-bot-$GITHUB_SHA.zip"
          RELEASE_LAYER="twitter-bot-$BRANCH"
          mkdir python
          pip install -r requirements.txt -t python
          zip --quiet -r $RELEASE_ID python

          # copy the file to S3 and install it in lambda layers
          aws lambda publish-layer-version --layer-name $RELEASE_LAYER --zip-file fileb://$RELEASE_ID --compatible-runtimes python3.8

# TODO add a step that will re-deploy the functions when the layer is updated
